[build]
    publish="build"

[[redirects]]
    from = "/"
    to = "/"
    status = 200

[[redirects]]
    from = "/menu"
    to = "/menu"
    status = 200

[[redirects]]
    from = "/sandwiches"
    to = "/sandwiches"
    status = 200
[[redirects]]
    from = "/specialties"
    to = "/specialties"
    status = 200
[[redirects]]
    from = "/bakery"
    to = "/bakery"
    status = 200
[[redirects]]
    from = "/cafe"
    to = "/cafe"
    status = 200
[[redirects]]
    from = "/contact"
    to = "/contact"
    status = 200
