[build]
    publish="build"

[[redirects]]

    from = "/*"
    to = "/"
    status = 200

    from = "/*"
    to = "/menu"
    status = 200

    from = "/*"
    to = "/sandwiches"
    status = 200

    from = "/*"
    to = "/specialties"
    status = 200

    from = "/*"
    to = "/bakery"
    status = 200

    from = "/*"
    to = "/cafe"
    status = 200

    from = "/*"
    to = "/contact"
    status = 200
